# Generated by Django 4.2.6 on 2023-10-16 16:30

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRates",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("local_currency_name", models.CharField(default="NGN", max_length=10)),
                ("local_amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ("foreign_currency_name", models.CharField(default="USD", max_length=10)),
                ("foreign_amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
