# Generated by Django 4.2.6 on 2023-10-17 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("fxrates", "0002_exchangerates_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastRates",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("local_amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ("foreign_amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                (
                    "rates",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_rates",
                        to="fxrates.exchangerates",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
