# Generated by Django 4.2.6 on 2023-10-18 13:13

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("fxrates", "0003_lastrates"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferToBanks",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("bank_name", models.CharField(default="Access Bank", max_length=250, unique=True)),
                ("account_number", models.CharField(default="Access Bank", max_length=20, unique=True)),
                ("account_name", models.CharField(default="John Doe", max_length=250, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
