# Generated by Django 4.2.6 on 2023-10-19 11:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("fxrates", "0004_transfertobanks"),
    ]

    operations = [
        migrations.CreateModel(
            name="FXRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ("currency", models.CharField(max_length=10)),
                ("account_number", models.CharField(max_length=20)),
                ("account_name", models.CharField(max_length=200)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fxrequest",
                        to="fxrates.transfertobanks",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
