# Generated by Django 4.2.6 on 2023-10-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fxrates", "0006_fxrequest_email_fxtransferrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="fxrequest",
            name="to_currency",
            field=models.CharField(default="NGN", max_length=10),
        ),
    ]
