# Generated by Django 4.2.6 on 2023-10-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_category_slug_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
