# Generated by Django 4.2.6 on 2023-10-16 14:41

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Subscriber Email")),
                ("active", models.BooleanField(default=True)),
                ("blog", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NewsMail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("subject", models.CharField(max_length=250, unique=True)),
                ("message", tinymce.models.HTMLField()),
                ("attachment", models.FileField(max_length=250, upload_to="newsletter", verbose_name="")),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="mails", to="newsletter.newsletter", verbose_name="Recipients"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
